# Generated by Django 4.2.11 on 2025-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='paintings/')),
            ],
        ),
    ]
