# Generated by Django 4.2.11 on 2025-04-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
